// <auto-generated />
using System;
using Isotainer.Module.Tank.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Isotainer.Module.Tank.Infrastructure.Database.Migrations
{
    [DbContext(typeof(TankContext))]
    partial class TankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Isotainer.Module.Tank.Core.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArchivedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("Isotainer.Module.Tank.Core.Entities.IsotainerTank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArchivedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LoadedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TankNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UnloadedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WashStatusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TankNumber")
                        .IsUnique();

                    b.HasIndex("WashStatusId");

                    b.ToTable("IsotainerTank", (string)null);
                });

            modelBuilder.Entity("Isotainer.Module.Tank.Core.Entities.WashStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArchivedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasMaxLength(200)
                        .HasColumnType("integer");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("WashStatus", (string)null);
                });

            modelBuilder.Entity("Isotainer.Module.Tank.Core.Entities.IsotainerTank", b =>
                {
                    b.HasOne("Isotainer.Module.Tank.Core.Entities.Company", "Company")
                        .WithMany("IsotainerTanks")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Isotainer.Module.Tank.Core.Entities.WashStatus", "WashStatus")
                        .WithMany("IsotainerTanks")
                        .HasForeignKey("WashStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("WashStatus");
                });

            modelBuilder.Entity("Isotainer.Module.Tank.Core.Entities.Company", b =>
                {
                    b.Navigation("IsotainerTanks");
                });

            modelBuilder.Entity("Isotainer.Module.Tank.Core.Entities.WashStatus", b =>
                {
                    b.Navigation("IsotainerTanks");
                });
#pragma warning restore 612, 618
        }
    }
}
