// <auto-generated />
using System;
using Isotainer.Module.Wash.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Isotainer.Module.Wash.Infrastructure.Database.Migrations
{
    [DbContext(typeof(WashContext))]
    [Migration("20260618093723_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Isotainer.Module.Wash.Core.Entities.WashInstruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArchivedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinishedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InstructedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IsotainerTankId")
                        .HasMaxLength(200)
                        .HasColumnType("uuid");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WashTypeId")
                        .HasMaxLength(200)
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WashTypeId");

                    b.ToTable("WashInstruction", (string)null);
                });

            modelBuilder.Entity("Isotainer.Module.Wash.Core.Entities.WashType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArchivedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Cost")
                        .HasPrecision(2)
                        .HasColumnType("double precision");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("WashType", (string)null);
                });

            modelBuilder.Entity("Isotainer.Module.Wash.Core.Entities.WashInstruction", b =>
                {
                    b.HasOne("Isotainer.Module.Wash.Core.Entities.WashType", "WashType")
                        .WithMany("WashInstructions")
                        .HasForeignKey("WashTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WashType");
                });

            modelBuilder.Entity("Isotainer.Module.Wash.Core.Entities.WashType", b =>
                {
                    b.Navigation("WashInstructions");
                });
#pragma warning restore 612, 618
        }
    }
}
